name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        with:
          ref: 'dev'
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn
      - name: Build app
        run: |
          yarn build-storybook
      - name: Generate docker image tag name
        id: generate-tag-name
        run: |
          export tag=${{ github.sha }}-$GITHUB_RUN_NUMBER
          echo $tag
          echo "::set-output name=docker_tag::$tag"
      - name: Build Docker Image
        id: build-image
        run: |
          docker build "$GITHUB_WORKSPACE/" -f "Dockerfile" -t harbor-us1.zilliz.cc/ued/zui-dev:${{ steps.generate-tag-name.outputs.docker_tag }}         
      - uses: azure/docker-login@v1
        with:
          login-server: harbor-us1.zilliz.cc
          username: ${{ secrets.HARBOR_USERNAME}}
          password: ${{ secrets.HARBOR_PASSWORD}}
      - name: Publish Docker Image to Harbor 
        if: "github.repository == 'zilliztech/zui'"
        id: publish-image
        run: |
          docker push harbor-us1.zilliz.cc/ued/zui-dev:${{ steps.generate-tag-name.outputs.docker_tag }}

      - name: Install OpenVPN and kubectl
        run: |
          sudo apt-get update
          sudo apt-get install openvpn -y
          sudo apt-get install -y apt-transport-https ca-certificates curl
          sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
          echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install kubectl -y

      - name: Connect VPN
        uses: golfzaptw/action-connect-ovpn@master
        id: connect_vpn
        with:
          FILE_OVPN: '.github/workflows/client.ovpn'
        env:
          CA_CRT: ${{ secrets.VPN_CA}}
          USER_CRT: ${{ secrets.VPN_CRT }}
          USER_KEY: ${{ secrets.VPN_KEY }}  
      - name: Deploy to cluster
        id: deploy 
        if: "github.repository == 'zilliztech/zui'"
        run: |
          echo ${{ secrets.kubeconfig }} > config64
          base64 -d config64 > kubeconfig
          kubectl set image deployment/zui-dev zui-dev=harbor-us1.zilliz.cc/ued/zui-dev:${{ steps.generate-tag-name.outputs.docker_tag }} -n ued --kubeconfig=kubeconfig